# Generated by Django 5.2.1 on 2025-05-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origin', models.CharField(max_length=100, verbose_name='产地')),
                ('description', models.TextField(verbose_name='商品描述')),
                ('image', models.ImageField(upload_to='products/', verbose_name='商品图片')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='库存')),
                ('xiaoliang', models.IntegerField(default=0, verbose_name='销量')),
                ('is_active', models.BooleanField(default=True, verbose_name='上架状态')),
            ],
        ),
    ]
